name: Generate Languages Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  languages:
    runs-on: ubuntu-latest

    steps:
      - name: Generate languages graph
        uses: DenverCoder1/github-readme-stats@main
        with:
          username: abiapcr
          output_path: languages.svg
          card_width: 320
          langs_count: 5
          layout: compact
          theme: tokyonight
          hide_border: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move generated file
        run: |
          mkdir -p languages-output
          mv languages.svg languages-output/languages.svg

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add languages-output/languages.svg
          git commit -m "Update languages stats" || exit 0
          git push
